const template = [
'<?xml version="1.0" encoding="utf-8"?>',
'<animated-vector xmlns:android="http://schemas.android.com/apk/res/android" xmlns:aapt="http://schemas.android.com/aapt" android:drawable="@drawable/{&vectorName}">',
'!1',
'	<target android:name="{&name}">',
'		<aapt:attr name="android:animation">',
'			<set android:ordering="{~ordering}">',
            '!objectAnimators',
'				<objectAnimator',
'					android:propertyName="{~propertyName}"',
'					android:valueType="{~valueType}"',
'					android:valueFrom="{~valueFrom}"',
'					android:valueTo="{~valueTo}"',
'					android:duration="{&duration}"',
'					android:repeatCount="{&repeatCount}"',
'					android:repeatMode="{~repeatMode}"',
'					android:startOffset="{~startOffset}"',
'					android:interpolator="{~interpolator}"',
'					android:fillAfter="{~fillAfter}"',
'					android:fillBefore="{~fillBefore}"',
'					android:fillEnabled="{~fillEnabled}">',
                '!propertyValues',
'					<propertyValuesHolder android:propertyName="{&propertyName}">',
                    '!keyframes',
'						<keyframe android:fraction="{~fraction}" android:valueType="{~valueType}" android:value="{~value}" />',
                    '!keyframes',
'					</propertyValuesHolder>',
                '!propertyValues',
'				</objectAnimator>',
            '!objectAnimators',
'			</set>',
'		</aapt:attr>',
'	</target>',
'!1',
'</animated-vector>'
];

export default template.join('\n');